# Generated by Django 6.0.2 on 2026-02-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=200)),
                ('search_volume', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('current_rank', models.IntegerField()),
                ('target_rank', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOOffPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('submission_url', models.URLField(max_length=255)),
                ('anchor_text', models.CharField(max_length=150)),
                ('da', models.IntegerField()),
                ('spam_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('live_status', models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOOnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_url', models.URLField(max_length=255)),
                ('title_optimized', models.BooleanField(default=False)),
                ('meta_optimized', models.BooleanField(default=False)),
                ('keyword_density', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mobile_friendly', models.BooleanField(default=True)),
                ('page_speed_status', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('seo_type', models.CharField(choices=[('on_page', 'On Page'), ('off_page', 'Off Page'), ('technical', 'Technical'), ('content', 'Content'), ('keyword', 'Keyword')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('broken_links', models.IntegerField(default=0)),
                ('sitemap_status', models.CharField(choices=[('updated', 'Updated'), ('submitted', 'Submitted')], max_length=20)),
                ('core_web_vitals_lcp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('core_web_vitals_cls', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('post_type', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('post_url', models.URLField(max_length=255)),
                ('posting_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GMBProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('total_reviews', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmb_profiles', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
