# Generated by Django 6.0.2 on 2026-02-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_details', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='seoonpage',
            name='seo_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onpage_metrics', to='seo.seotask'),
        ),
        migrations.AddField(
            model_name='seooffpage',
            name='seo_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offpage_activities', to='seo.seotask'),
        ),
        migrations.AddField(
            model_name='seokeywords',
            name='seo_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_tracking', to='seo.seotask'),
        ),
        migrations.AddField(
            model_name='seotechnical',
            name='seo_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_audits', to='seo.seotask'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='socialmetrics',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='seo.socialmediapost'),
        ),
    ]
